### ISSUE TITLE
The automerge storage docs link is broken

### ISSUE THREAD

**Issue by fdb** [automerge/old-automerge-website#31]
Here's the page about the binary document format:

https://automerge.org/docs/how-it-works/binary-format/

It links to this page:

https://alexjg.github.io/automerge-storage-docs/

However, that link is down. I also couldn't find where the original page should be.

Here's the latest working version from archive.org:

https://web.archive.org/web/20230131145048/https://alexjg.github.io/automerge-storage-docs/

cc @alexjg

**Comment by alexjg** [comment]
Ah this is because I moved it to https://github.com/automerge/automerge-binary-format-spec and forgot to set up a redirect. It should be working now.

**Comment by fdb** [comment]
Thanks! 👍
